# Generated by Django 4.2.7 on 2025-07-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司名称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('subject', models.CharField(max_length=200, verbose_name='询价主题')),
                ('message', models.TextField(verbose_name='询价内容')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='产品名称')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='数量')),
                ('status', models.CharField(choices=[('new', '新询价'), ('processing', '处理中'), ('replied', '已回复'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, verbose_name='回复内容')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='来源')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '询价咨询',
                'verbose_name_plural': '询价咨询',
                'ordering': ['-created_at'],
            },
        ),
    ]
