# Generated by Django 4.2.7 on 2025-07-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='优势标题')),
                ('description', models.TextField(verbose_name='优势描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('image', models.ImageField(blank=True, upload_to='advantages/', verbose_name='优势图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业优势',
                'verbose_name_plural': '企业优势',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='证书名称')),
                ('description', models.TextField(blank=True, verbose_name='证书描述')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='证书图片')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='颁发日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资质证书',
                'verbose_name_plural': '资质证书',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='信息键')),
                ('value', models.TextField(verbose_name='信息值')),
                ('info_type', models.CharField(choices=[('basic', '基本信息'), ('contact', '联系信息'), ('social', '社交媒体'), ('stats', '统计数据'), ('other', '其他信息')], default='basic', max_length=20, verbose_name='信息类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'ordering': ['info_type', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FactoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='图片标题')),
                ('description', models.TextField(blank=True, verbose_name='图片描述')),
                ('image', models.ImageField(upload_to='factory/', verbose_name='工厂图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工厂图片',
                'verbose_name_plural': '工厂图片',
                'ordering': ['order', 'title'],
            },
        ),
    ]
