# Generated by Django 4.2.7 on 2025-11-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="友链网站的显示名称",
                        max_length=200,
                        verbose_name="网站名称",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="友链网站的完整URL", verbose_name="网站链接"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="网站简短描述（可选）",
                        max_length=500,
                        verbose_name="描述",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="友链网站的Logo（可选）",
                        null=True,
                        upload_to="friend_links/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="是否添加nofollow属性（SEO控制）",
                        verbose_name="NoFollow",
                    ),
                ),
                (
                    "target_blank",
                    models.BooleanField(
                        default=True,
                        help_text="是否在新窗口打开链接",
                        verbose_name="新窗口打开",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "友情链接",
                "verbose_name_plural": "友情链接",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="advantage",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "企业优势",
                "verbose_name_plural": "企业优势",
            },
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "证书",
                "verbose_name_plural": "证书",
            },
        ),
        migrations.AlterModelOptions(
            name="companyinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "公司信息",
                "verbose_name_plural": "公司信息",
            },
        ),
        migrations.RemoveField(
            model_name="advantage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="info_type",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="key",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="order",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="value",
        ),
        migrations.AddField(
            model_name="advantage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="address",
            field=models.CharField(blank=True, max_length=500, verbose_name="地址"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="公司描述"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="公司名称"
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="电话"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="website",
            field=models.URLField(blank=True, verbose_name="网站"),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="description",
            field=models.TextField(verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="图标类名或SVG",
                max_length=100,
                verbose_name="图标",
            ),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="factoryimage",
            name="image",
            field=models.ImageField(
                upload_to="factory_images/", verbose_name="工厂图片"
            ),
        ),
    ]
