# Generated by Django 4.2.7 on 2025-07-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标签别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='文章别名')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('excerpt', models.TextField(blank=True, verbose_name='文章摘要')),
                ('featured_image', models.ImageField(blank=True, upload_to='articles/', verbose_name='特色图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO关键词')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
