# Generated by Django 4.2.7 on 2025-07-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('frontend', '前端内容'), ('product', '产品内容'), ('category', '分类内容'), ('all', '所有内容')], max_length=20, verbose_name='翻译类型')),
                ('target_language', models.CharField(max_length=10, verbose_name='目标语言')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=10, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('logs', models.TextField(blank=True, verbose_name='详细日志')),
                ('items_processed', models.IntegerField(default=0, verbose_name='处理项目数')),
                ('items_success', models.IntegerField(default=0, verbose_name='成功项目数')),
                ('items_failed', models.IntegerField(default=0, verbose_name='失败项目数')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '翻译日志',
                'verbose_name_plural': '翻译日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='翻译管理', max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '翻译管理',
                'verbose_name_plural': '翻译管理',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='技术规格'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='图片'),
        ),
    ]
