# Generated by Django 4.2.7 on 2025-08-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_translationlog_translationmanagement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationlog",
            name="translation_type",
            field=models.CharField(
                choices=[
                    ("frontend", "前端内容"),
                    ("product", "产品内容"),
                    ("category", "分类内容"),
                    ("article", "资讯内容"),
                    ("all", "所有内容"),
                ],
                max_length=20,
                verbose_name="翻译类型",
            ),
        ),
    ]
