# Generated by Django 4.2.7 on 2025-09-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_translationlog_translation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="categories/", verbose_name="分类图片"
            ),
        ),
    ]
