# Generated by Django 4.2.7 on 2025-10-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_subcategory_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规格名称")),
                ("value", models.TextField(verbose_name="规格值")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_items",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品技术规格",
                "verbose_name_plural": "产品技术规格",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="特性名称")),
                ("description", models.TextField(verbose_name="特性描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_items",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品特性",
                "verbose_name_plural": "产品特性",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="应用名称")),
                ("description", models.TextField(verbose_name="应用描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_items",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品应用领域",
                "verbose_name_plural": "产品应用领域",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
