# Generated by Django 4.2.7 on 2025-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productspecification_productfeature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.CharField(
                blank=True,
                default="Silver, White, Black, Bronze, Champagne, Golden or customized",
                max_length=300,
                verbose_name="Colors",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="grade",
            field=models.CharField(
                blank=True, default="6063 Series", max_length=100, verbose_name="Grade"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="range_param",
            field=models.CharField(
                blank=True,
                default="OEM factory supply aluminium profiles",
                max_length=200,
                verbose_name="Range",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="surface_treatment",
            field=models.CharField(
                blank=True,
                default="Mill Finished, Anodized, Powder Coated, Electrohoresis, Wood Grain",
                max_length=300,
                verbose_name="Surface Treatment",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="temper",
            field=models.CharField(
                blank=True, default="T5, T6", max_length=100, verbose_name="Temper"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type_param",
            field=models.CharField(
                blank=True,
                default="For door and window profiles",
                max_length=200,
                verbose_name="Type",
            ),
        ),
    ]
