# Generated by Django 4.2.7 on 2025-11-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_colors_product_grade_product_range_param_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="模板的显示名称",
                        max_length=200,
                        verbose_name="模板名称",
                    ),
                ),
                (
                    "range_param",
                    models.CharField(
                        blank=True,
                        default="OEM factory supply aluminium profiles",
                        max_length=200,
                        verbose_name="Range",
                    ),
                ),
                (
                    "type_param",
                    models.CharField(
                        blank=True,
                        default="For door and window profiles",
                        max_length=200,
                        verbose_name="Type",
                    ),
                ),
                (
                    "surface_treatment",
                    models.CharField(
                        blank=True,
                        default="Mill Finished, Anodized, Powder Coated, Electrohoresis, Wood Grain",
                        max_length=300,
                        verbose_name="Surface Treatment",
                    ),
                ),
                (
                    "colors",
                    models.CharField(
                        blank=True,
                        default="Silver, White, Black, Bronze, Champagne, Golden or customized",
                        max_length=300,
                        verbose_name="Colors",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        default="6063 Series",
                        max_length=100,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "temper",
                    models.CharField(
                        blank=True,
                        default="T5, T6",
                        max_length=100,
                        verbose_name="Temper",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="产品描述")),
                (
                    "features_text",
                    models.TextField(blank=True, verbose_name="特性文本"),
                ),
                (
                    "applications_text",
                    models.TextField(blank=True, verbose_name="应用文本"),
                ),
                (
                    "specifications_text",
                    models.TextField(blank=True, verbose_name="规格文本"),
                ),
                (
                    "packaging_details",
                    models.TextField(blank=True, verbose_name="包装详情"),
                ),
                (
                    "oem_available",
                    models.BooleanField(default=True, verbose_name="支持OEM"),
                ),
                (
                    "free_samples",
                    models.CharField(
                        blank=True,
                        default="Available, about 1 days can be sent",
                        max_length=200,
                        verbose_name="免费样品",
                    ),
                ),
                (
                    "supply_ability",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="供应能力"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="付款方式"
                    ),
                ),
                (
                    "product_origin",
                    models.CharField(
                        blank=True,
                        default="Foshan China",
                        max_length=200,
                        verbose_name="产品产地",
                    ),
                ),
                (
                    "shipping_port",
                    models.CharField(
                        blank=True,
                        default="Shenzhen/Guangzhou/Foshan",
                        max_length=200,
                        verbose_name="发货港口",
                    ),
                ),
                (
                    "lead_time",
                    models.CharField(
                        blank=True,
                        default="7-15 Days",
                        max_length=200,
                        verbose_name="交期",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="如果设置，该分类下的产品可以使用此模板",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="products.category",
                        verbose_name="关联分类",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="如果设置，该子分类下的产品可以使用此模板（优先级高于分类模板）",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="products.subcategory",
                        verbose_name="关联子分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品模板",
                "verbose_name_plural": "产品模板",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规格名称")),
                ("value", models.TextField(verbose_name="规格值")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_items",
                        to="products.producttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板技术规格",
                "verbose_name_plural": "模板技术规格",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="特性名称")),
                ("description", models.TextField(verbose_name="特性描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_items",
                        to="products.producttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板特性",
                "verbose_name_plural": "模板特性",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateFactoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="图片标题")),
                ("description", models.TextField(blank=True, verbose_name="图片描述")),
                (
                    "image",
                    models.ImageField(
                        upload_to="template_factory/", verbose_name="工厂图片"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="如：factory, production, quality, packaging",
                        max_length=50,
                        verbose_name="图片分类",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_images",
                        to="products.producttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板工厂图片",
                "verbose_name_plural": "模板工厂图片",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="应用名称")),
                ("description", models.TextField(verbose_name="应用描述")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="template_applications/",
                        verbose_name="应用场景图片",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_items",
                        to="products.producttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板应用领域",
                "verbose_name_plural": "模板应用领域",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
