# Generated by Django 4.2.7 on 2025-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_add_product_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="productapplication",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                verbose_name="应用场景图片",
            ),
        ),
    ]
