# Generated by Django 4.2.7 on 2025-11-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_add_application_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="如果指定，优先使用此模板；否则自动匹配分类/子分类模板",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.producttemplate",
                verbose_name="关联模板",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="use_template",
            field=models.BooleanField(
                default=True,
                help_text="如果为False，则不使用任何模板，只使用产品自定义数据",
                verbose_name="使用模板内容",
            ),
        ),
        migrations.CreateModel(
            name="TemplateProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：阳极氧化、粉末喷涂、电泳、木纹转印等",
                        max_length=200,
                        verbose_name="工艺名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="详细的工艺处理说明", verbose_name="工艺描述"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="template_process/",
                        verbose_name="工艺图片",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_items",
                        to="products.producttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板工艺处理",
                "verbose_name_plural": "模板工艺处理",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
